[workspace]
resolver = "3"
members = [
    "app",
    "bindings/py",
    "bindings/wasm",
    "crates/hanconv",
    "crates/hanconv-app",
    "crates/hanconv-cli",
]

[workspace.dependencies]
hanconv = "0.5"
