[package]
name = "hanconv-py"
version = "0.3.0"
edition = "2024"

[lib]
name = "hanconv"
crate-type = ["cdylib"]

[dependencies]
hanconv = { workspace = true }
pyo3 = { version = "0.27", features = ["extension-module"] }
